variables:
  - &test_image 'docker.osgeo.org/postgis/build-test:trisquel3'
  - common_doc_paths: &common_doc_paths
      # related config files
      - ".woodpecker/docs.yml"
      # Makefiles
      - "doc/Makefile.in"
      - "doc/html/images/Makefile.in"
      # XML sources
      - "doc/*.xml"
      # Internationalization Makefiles
      - "doc/po/Makefile.local"
  - &when_path
      include:
        - <<: *common_doc_paths
  - &when_path_full
      include:
        - <<: *common_doc_paths
        # Any localized assets
        - "doc/po/*/Makefile.in"
        - "doc/po/*/*.po"

steps:
  prepare:
    image: *test_image
    pull: true
    commands:
      - ./autogen.sh
      - mkdir -p build-docs && cd build-docs
      - ../configure --without-pg --without-protobuf --without-raster
      - make postgis_revision.h
    when:
      path: *when_path_full
  check-xml:
    image: *test_image
    group: check-xml-and-build-images
    commands:
      - make -C build-docs/doc check
    when:
      path: *when_path
  build-images:
    image: *test_image
    group: check-xml-and-build-images
    commands:
      - make -C build-docs/doc images
    when:
      path: *when_path
  build-html:
    image: *test_image
    group: output
    commands:
      - make -C build-docs/doc html
    when:
      path: *when_path
  build-cheatsheets:
    image: *test_image
    group: output
    commands:
      - make -C build-docs/doc/ cheatsheets
    when:
      path: *when_path_full
  build-chunked-html:
    image: *test_image
    group: output
    commands:
      - make -C build-docs/doc html
    when:
      path: *when_path
  build-pdf:
    image: *test_image
    group: output
    commands:
      - make -C build-docs/doc/ pdf
    when:
      path: *when_path

  # DO NOT EDIT PAST THIS LINE, use update-docs-localized.sh to update #
### TARGET check-xml
  check-xml-ja:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/ja local-check-xml
    group: localized-check-xml
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  check-xml-de:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/de local-check-xml
    group: localized-check-xml
    when:
      path:
        include:
          - "doc/po/de/*.po"
  check-xml-fr:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/fr local-check-xml
    group: localized-check-xml
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  check-xml-zh_Hans:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/zh_Hans local-check-xml
    group: localized-check-xml
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
### TARGET html
  html-ja:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/ja local-html
    group: localized-html
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  html-de:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/de local-html
    group: localized-html
    when:
      path:
        include:
          - "doc/po/de/*.po"
  html-fr:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/fr local-html
    group: localized-html
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  html-zh_Hans:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/zh_Hans local-html
    group: localized-html
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
### TARGET cheatsheets
  cheatsheets-ja:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/ja local-cheatsheets
    group: localized-cheatsheets
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  cheatsheets-de:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/de local-cheatsheets
    group: localized-cheatsheets
    when:
      path:
        include:
          - "doc/po/de/*.po"
  cheatsheets-fr:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/fr local-cheatsheets
    group: localized-cheatsheets
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  cheatsheets-zh_Hans:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/zh_Hans local-cheatsheets
    group: localized-cheatsheets
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
### TARGET check-cheatsheets
  check-cheatsheets-ja:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/ja local-check-cheatsheets
    group: localized-check-cheatsheets
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  check-cheatsheets-de:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/de local-check-cheatsheets
    group: localized-check-cheatsheets
    when:
      path:
        include:
          - "doc/po/de/*.po"
  check-cheatsheets-fr:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/fr local-check-cheatsheets
    group: localized-check-cheatsheets
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  check-cheatsheets-zh_Hans:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/zh_Hans local-check-cheatsheets
    group: localized-check-cheatsheets
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
### TARGET pdf
  pdf-ja:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/ja local-pdf
    group: localized-pdf
    when:
      path:
        include:
          - "doc/po/ja/*.po"
  pdf-de:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/de local-pdf
    group: localized-pdf
    when:
      path:
        include:
          - "doc/po/de/*.po"
  pdf-fr:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/fr local-pdf
    group: localized-pdf
    when:
      path:
        include:
          - "doc/po/fr/*.po"
  pdf-zh_Hans:
    image: *test_image
    commands:
      - make -C build-docs/doc/po/zh_Hans local-pdf
    group: localized-pdf
    when:
      path:
        include:
          - "doc/po/zh_Hans/*.po"
