pipeline:
  prepare:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    pull: true
    commands:
      - ./autogen.sh
      - mkdir -p build-docs && cd build-docs
      - ../configure --without-pg
      - make postgis_revision.h
  build-html:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - cd build-docs
      - make docs
      - make -C doc check
      - make docs-localized
      - make -C doc/ check-localized
  build-pdf:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - cd build-docs
      - make -C doc/ pdf
  build-cheatsheets:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - cd build-docs
      - make -C doc/ cheatsheets
