matrix:
  TR:
    - it_IT
    - pt_BR
    - fr
    - es
    - pl
    - ko_KR
    - de
    - ja
    - ru

pipeline:
  prepare:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    pull: true
    commands:
      - ./autogen.sh
      - mkdir -p build-docs && cd build-docs
      - ../configure --without-pg
      - make postgis_revision.h
    when:
      path: "doc/po/${TR}/*.po"
  check-xml:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - make -C build-docs/doc/po/${TR} local-check
    when:
      path: "doc/po/${TR}/*.po"
  build-html:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - make -C build-docs/doc/po/${TR} local-html
    when:
      path: "doc/po/${TR}/*.po"
  build-pdf:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - make -C build-docs/doc/po/${TR} local-pdf
    when:
      path: "doc/po/${TR}/*.po"
  build-cheatsheets:
    image: docker.osgeo.org/postgis/build-test:trisquel3
    commands:
      - make -C build-docs/doc/po/${TR} local-cheatsheets
    when:
      path: "doc/po/${TR}/*.po"
